[directories]
alacritty = "$DOTFILES_DIRECTORY/.config/alacritty"
dotfiles = "$DOTFILES_DIRECTORY"
fish = "$DOTFILES_DIRECTORY/.config/fish/"
i3 = "$DOTFILES_DIRECTORY/.config/i3/"
neovim = "$DOTFILES_DIRECTORY/.config/nvim/"
nixos = "$DOTFILES_DIRECTORY/.config/nixos/"
projects = "$HOME/Projects/"
ssh = "$HOME/.ssh/"
sway = "$DOTFILES_DIRECTORY/.config/sway/"
tmux = "$DOTFILES_DIRECTORY/.config/tmux/"
