services:
    backblaze:
        image: tessypowder/backblaze-personal-wine:latest
        restart: always
        ports:
            - "8080:5800"
        volumes:
            - /home/cyrus/.config/backblaze/:/config/
            - /mnt/backup/:/drive_d/
            - /mnt/hdd/:/drive_e/
            - /mnt/games/:/drive_f/
            - /mnt/virtual-machines/:/drive_g/
