[general]
import = ["~/.config/alacritty/themes/dracula.toml"]
live_config_reload = true

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = true

[font]
size = 12.0

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"
style = "Bold Italic"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
dynamic_title = false

[keyboard]
bindings = [
    { key = "Home", mods = "Control", mode = "~AppCursor", action = "First" },
    { key = "End", mods = "Control", mode = "~AppCursor", action = "Last" },
    { key = "Back", mods = "Control", chars = "\\x17" },
]
