[files]
alacritty = "$DOTFILES_DIRECTORY/.config/alacritty/alacritty.toml"
change-fzf = "$DOTFILES_DIRECTORY/.config/change-fzf/directories.toml"
dotfiles = "$DOTFILES_DIRECTORY"
edit-fzf = "$DOTFILES_DIRECTORY/.config/edit-fzf/files.toml"
fish = "$DOTFILES_DIRECTORY/.config/fish/"
hyprland = "$DOTFILES_DIRECTORY/.config/hypr/"
i3 = "$DOTFILES_DIRECTORY/.config/i3/"
neovim = "$DOTFILES_DIRECTORY/.config/nvim/"
niri = "$DOTFILES_DIRECTORY/.config/niri/"
nixos = "$DOTFILES_DIRECTORY/.config/nixos/"
playground = "$HOME/Playground/"
ssh = "$HOME/.ssh/"
sway = "$DOTFILES_DIRECTORY/.config/sway/"
tmux = "$DOTFILES_DIRECTORY/.config/tmux/tmux.conf"
